spring: 
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: jdbc:postgresql://localhost:5432/tacocloud
        username: jarvis
        password: ilnur@089
    
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always